baseURL = "yuehao1995.github.io"
languageCode = "zh-CN"
title = "张岳灏的博客"
theme = "maupassant"

[Permalinks]
   post= "/:sections/:year/:month/:day/:slug/"

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

[author]
  name = "张岳灏"

[params]
  author = "张岳灏"
  subtitle = "专注于Java、Go语言(golang)、在学习c,python及计算机网络,操作系统，unix高级编程，英语等"
  keywords = "golang,go语言,go语言笔记,张岳灏,java,python,c,博客,计算机基础,计算机网络,操作系统,自动部署"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、c、Python、计算机基础，自动化部署等"

[menu]
  [[menu.main]]
    identifier = "books"
    name = "新书"
    url = "/books/"
    weight = 2
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
